Reverse Mapping:
  nodetype: function
  output_path:
  module: mapping
  function: nt_mapping
  package:
  variables:
    binary_to_nt: False

Error Correction Decoder:
  nodetype: function
  output_path:
  module: ecc
  function: decode
  package:
  variables:
    rate: "1/3"

Decompression:
  nodetype: function
  module: huffman_compression
  function: decompress
  package: custom
  variables:
    json_input: test_results/stage1/rev_codebook.json
    output_path: test_results/stage4/results.txt