Environment:
  Input Path: test_data/short_data.txt
  Directory (Result): test_a
  Directory (Log): test_a

Compression:
  nodetype: function
  module: huffman
  function: compress
  package: modules
  variables:
    reverse_filename: reverse_codebook.json
    forward_filename: forward_codebook.json

Error Correction Encoder:
  nodetype: function
  module: turboECC
  function: encode
  package: modules
  variables:
    rate: '1/3'

Forward Mapping:
  nodetype: function
  module: mapping
  function: nt_mapping
  package: modules
  variables:

Write Ground Truth:
  nodetype: function
  module: PCR_simulator
  function: create_ground_truth
  package: modules
  variables:
    filename: ground_truth.fasta

Signal Generator:
  nodetype: function
  module: signal
  function: generate_signal
  package: modules
  variables:

Basecaller:
  nodetype: command
  command: bonito basecaller --batchsize 16 --chunksize 2000 dna_r9.4.1_e8.1_sup@v3.3 results/stage4/signals > results/stage4/output.fastq
  outfile: output.fastq
  variables:

PCR Simulator (Weighted):
  nodetype: function
  module: PCR_simulator
  function: create_weighted_fasta
  package:
  variables:
    gt_path: results/stage4/ground_truth.fasta
    directory: results/stage4/weighted
    weight: 100

Consensus Alignment:
  nodetype: function
  module: alignment
  function: align_sequences
  package: modules
  variables:
    wrapper: clustalw
    filename: consensus.txt
    variables:

Reverse Mapping:
  nodetype: function
  module: mapping
  function: nt_mapping
  package: modules
  variables:
    binary_to_nt: False

Error Correction Decoder:
  nodetype: function
  module: turboECC
  function: decode
  package: modules
  variables:
    rate: "1/3"

Decompression:
  nodetype: function
  module: huffman_compression
  function: decompress
  package: modules
  variables:
    reverse_filename: reverse_codebook.json