#Refer to template.yaml for configuration reference

Environment:
  input: test_data/short_data.txt
  name: E1    #Subfolder

Compression:
  nodetype: function
  module: huffman
  function: compress
  package: modules
  variables:
    reverse_filename: reverse_codebook.json
    forward_filename: forward_codebook.json

Error Correction Encoder:
  nodetype: function
  module: euclid
  function: euclidEncode
  package: modules
  variables:
    filepath: Euclid/gcTrackingSymbolSize4.npy
    assignMech: 'track'
    segment_length: 300

Signal Generator:
  nodetype: function
  module: signal
  function: generate_signal
  package: modules
  variables:
    encode: true

Basecaller:
  nodetype: function
  module: basecaller
  function: bonito
  package: modules
  variables:
    batchsize: 16
    chunksize: 2000