Compression:
  nodetype: function
  output_path:
  module: huffman_compression
  function: compress
  package: custom
  variables:
    json_output: test_results/stage4/rev_codebook.json

Error Correction Encoder:
  nodetype: function
  output_path:
  module: ecc
  function: encode
  package:
  variables:
    rate: '1/3'

Forward Mapping:
  nodetype: function
  output_path:
  module: mapping
  function: nt_mapping
  package:
  variables:
    output_path: test_results/stage4/dna_test_sequence.txt

Write Ground Truth:
  nodetype: function
  output_path:
  module: pcr_simulator
  function: create_ground_truth
  package:
  variables:
    filepath: test_results/stage4/ground_truth.fasta

Signal Generator:
  nodetype: function
  output_path:
  module: signal_generator
  function: generate_signal
  package:
  variables:
    file_prefix: read
    directory: test_results/stage4/signals

Basecaller:
  nodetype: command
  command: bonito basecaller --batchsize 16 --chunksize 2000 dna_r9.4.1_e8.1_sup@v3.3 test_results/stage4/signals > test_results/stage4/output.fastq
  output_path: test_results/stage4/output.fastq
  variables:

PCR Simulator (Weighted):
  nodetype: function
  output_path:
  module: pcr_simulator
  function: create_weighted_fasta
  package:
  variables:
    gt_path: test_results/stage4/ground_truth.fasta
    directory: test_results/stage4/weighted
    weight: 100

Consensus Alignment:
  nodetype: function
  output_path:
  module: alignIO_wrapper
  function: align_sequences
  package:
  variables:
    wrapper: clustalw
    filepath: test_results/stage4/consensus.txt
    variables:

Reverse Mapping:
  nodetype: function
  output_path:
  module: mapping
  function: nt_mapping
  package:
  variables:
    binary_to_nt: False

Error Correction Decoder:
  nodetype: function
  output_path:
  module: ecc
  function: decode
  package:
  variables:
    rate: "1/3"

Decompression:
  nodetype: function
  module: huffman_compression
  function: decompress
  package: custom
  variables:
    json_input: test_results/stage4/rev_codebook.json
    output_path: test_results/stage4/results.txt
