Environment:
  input: test_data/short_data.txt
  name: A1    #Subfolder
  results:    #Optional - specific results directory if needed, default to results in current directory. Delete if not used
  logs:       #Optional - specific logs directory if needed, defaults to logs in current directory. Delete if not used
  stages:     #Optional - specific stages directory if needed, defaults to stages in current directory. Delete if not used

NodeFunction:
  nodetype: function
  module: huffman
  function: compress
  package: modules
  variables:
    reverse_filename: reverse_codebook.json
    forward_filename: forward_codebook.json

NodeCLICommand:
  nodetype: command
  command: bonito basecaller --batchsize 16 --chunksize 2000 dna_r9.4.1_e8.1_sup@v3.3 results/stage4/signals > results/stage4/output.fastq
  outfile: output.fastq
  variables: