Environment:
  Input Path: test_data/short_data.txt
  Directory (Result): test_one
  Directory (Log): test_one

NodeFunction:
  nodetype: function
  output_path:
  module: huffman
  function: compress
  package: modules
  variables:
    reverse_filename: reverse_codebook.json
    forward_filename: forward_codebook.json

NodeCLICommand:
  nodetype: command
  command: bonito basecaller --batchsize 16 --chunksize 2000 dna_r9.4.1_e8.1_sup@v3.3 results/stage4/signals > results/stage4/output.fastq
  outfile: output.fastq
  variables: