NodeFunction:
  name:
  nodetype:
  input_type:
  output_type:
  output_path:
  module:
  function:
  package:
  variables:

NodeCLICommand:
  name:
  nodetype:
  input_type:
  output_type:
  command:
  output_path:
  variables:

